Repository kudobuilder/operators, pull requests merged in 2019-09, with the labels that each got.

#74 Kafka: add advanced health checks
  repository/kafka/docs/latest/configuration.md
  repository/kafka/docs/latest/release-notes.md
  repository/kafka/operator/operator.yaml
  repository/kafka/operator/params.yaml
  repository/kafka/operator/templates/health-check.yaml
  repository/kafka/operator/templates/statefulset.yaml
Labels: approved, needs-kind, ok-to-test, size/L

#72 updates for kudo 0.5.0, now using kudo update and kudo upgrade commands
  repository/elastic/docs/README.md
  repository/elastic/operator/operator.yaml
Labels: approved, lgtm, needs-kind, size/M

#75 Bump to 0.6.0 Testing
  Makefile
Labels: approved, needs-kind, size/XS

#76 zookeeper: change image and add some params
  repository/zookeeper/operator/operator.yaml
  repository/zookeeper/operator/params.yaml
  repository/zookeeper/operator/templates/bootstrap.sh.yaml
  repository/zookeeper/operator/templates/healthcheck.sh.yaml
  repository/zookeeper/operator/templates/services.yaml
  repository/zookeeper/operator/templates/statefulset.yaml
  repository/zookeeper/operator/templates/validation.yaml
  repository/zookeeper/tests/zookeeper-upgrade-test/00-install.yaml
  repository/zookeeper/tests/zookeeper-upgrade-test/01-resize.yaml
Labels: approved, needs-kind, size/L

#78 remove ref to dc/os
  repository/kafka/docs/v0.1/resources/grafana-dashboard.json
Labels: approved, needs-kind, size/XS

#77 structure change for maintainers in 0.7.0
  kudo-test.yaml
  repository/elastic/operator/operator.yaml
  repository/flink/docs/demo/financial-fraud/README.md
  repository/flink/operator/operator.yaml
  repository/kafka/operator/operator.yaml
  repository/mysql/operator/operator.yaml
  repository/redis/operator/operator.yaml
  repository/zookeeper/operator/operator.yaml
Labels: approved, do-not-merge/hold, needs-kind, size/M
