Repository kudobuilder/operators, pull requests merged in 2019-08, with the labels that each got.

#63 adding owners file for ci process
  .gitignore
  OWNERS
Labels: kind/cleanup, lgtm, size/S

#62 Bump kudo to 0.5.0, clean up testing Makefile.
  .circleci/config.yml
  .gitignore
  Makefile
  docs/Developing.md
  kudo-test.yaml
  repository/zookeeper/tests/zookeeper-upgrade-test/00-assert.yaml
  repository/zookeeper/tests/zookeeper-upgrade-test/01-assert.yaml
  test/kind/kubernetes-1.12.9.yaml
  test/kind/kubernetes-1.13.7.yaml
  test/kind/kubernetes-1.14.3.yaml
  test/kind/kubernetes-1.15.0.yaml
  test/manifests/local-path-storage.yaml
Labels: approved, kind/cleanup, size/L

#65 Ignore 'lost+found' folder when initialising DB
  repository/mysql/operator/templates/mysql.yaml
Labels: approved, kind/bug, lgtm, size/XS

#64 Kafka upgrade docs refreshed
  repository/kafka/docs/v0.2/upgrade.md
Labels: approved, needs-kind, retest-not-required-docs-only, size/M

#69 k8s min version is 1.15 not 1.5
  repository/flink/docs/demo/financial-fraud/demo-operator/operator.yaml
  repository/flink/operator/operator.yaml
  repository/kafka/operator/operator.yaml
  repository/mysql/operator/operator.yaml
  repository/zookeeper/operator/operator.yaml
Labels: approved, needs-kind, size/S

#71 kafka: update references from 0.1.1 to 0.1.2
  repository/flink/docs/demo/financial-fraud/README.md
  repository/flink/docs/demo/financial-fraud/demo-operator/templates/kafka.yaml
  repository/kafka/README.md
  repository/kafka/docs/latest/install.md
  repository/kafka/docs/latest/update.md
  repository/kafka/docs/latest/upgrade.md
  repository/kafka/docs/v0.1/install.md
  repository/kafka/docs/v0.2/install.md
  repository/kafka/docs/v0.2/update.md
  repository/kafka/docs/v0.2/upgrade.md
  repository/kafka/operator/operator.yaml
Labels: approved, kind/cleanup, size/M
